-- Flasks
FLASK_OF_THE_TITANS = {
    buffID=17626,
    itemID=13510,
}
FLASK_OF_SUPREME_POWER = {
    buffID=17628,
    itemID=13512,
}
FLASK_OF_DISTILLED_WISDOM = {
    buffID=17627,
    itemID=13511,
}
FLASK_OF_CHROMATIC_RESISTANCE = {
    buffID=17629,
    itemID=13513,
}

-- Blasted Lands Consumables
LUNG_JUICE_COCKTAIL = {
    buffID=10668,
    itemID=8411,
}
GROUND_SCORPOK_ASSAY = {
    buffID=10669,
    itemID=8412,
}
CEREBRAL_CORTEX_COMPOUND = {
    buffID=10692,
    itemID=8423,
}
GIZZARD_GUM = {
    buffID=10693,
    itemID=8424,
}
ROIDS = {
    buffID=10667,
    itemID=8410,
}

-- Elixirs
ARCANE_ELIXIR = {
    buffID=11390,
    itemID=9155,
}
ELIXIR_OF_GIANTS = {
    buffID=11405,
    itemID=9206,
}
ELIXIR_OF_GREATER_AGILITY = {
    buffID=11334,
    itemID=9187,
}
ELIXIR_OF_THE_MONGOOSE = {
    buffID=17538,
    itemID=17571,
}
ELIXIR_OF_SUPERIOR_DEFENSE = {
    buffID=11348,
    itemID=13445,
}
GIFT_OF_ARTHAS = {
    buffID=11371,
    itemID=9088,
}
GREATER_ARCANE_ELIXIR = {
    buffID=17539,
    itemID=13454,
}
ELIXIR_OF_GREATER_FIREPOWER = {
    buffID=26276,
    itemID=21547,
}
ELIXIR_OF_SHADOW_POWER = {
    buffID=11474,
    itemID=9264,
}
ELIXIR_OF_FROST_POWER = {
    buffID=21920,
    itemID=17708,
}
MAGEBLOOD_POTION = {
    buffID=24363,
    itemID=20007,
}

-- Jujus/Winterspring
JUJU_POWER = {
    buffID=16323,
    itemID=12451,
}
JUJU_MIGHT = {
    buffID=16329,
    itemID=12460,
}
WINTERFALL_FIREWATER = {
    buffID=17038,
    itemID=12820,
}

-- Well Fed Buffs
-- Unique Buffs
BLESSED_SUNFRUIT = {
    buffID=18125,
    itemID=13810,
}
GRILLED_SQUID = {
    buffID=18192,
    itemID=13928,
}
NIGHTFIN_SOUP = {
    buffID=18194,
    itemID=13931,
}
RUNN_TUM_TUBER_SURPRISE = {
    buffID=22730,
    itemID=18254,
}
SMOKED_DESERT_DUMPLINGS = {
    buffID=24799,
    itemID=20452,
}
DIRGES_KICKIN_CHIMAEROK_CHOPS = {
    buffID=25661,
    itemID=21023,
}

-- 12 sta/spi (all foods share the same buff)
TENDER_WOLF_STEAK = {
    buffID=19710,
    itemID=18045,
}


CONSUMABLES_BY_CLASSES = {
    ["DRUID"] = {
        ELIXIR_OF_GIANTS,
        ELIXIR_OF_GREATER_AGILITY,
        ELIXIR_OF_THE_MONGOOSE,
        ELIXIR_OF_SUPERIOR_DEFENSE,
        FLASK_OF_SUPREME_POWER,
        GIFT_OF_ARTHAS,
        GREATER_ARCANE_ELIXIR,
        MAGEBLOOD_POTION,
        LUNG_JUICE_COCKTAIL,
        GROUND_SCORPOK_ASSAY,
        CEREBRAL_CORTEX_COMPOUND,
        GIZZARD_GUM,
        ROIDS,
        JUJU_POWER,
        JUJU_MIGHT,
        WINTERFALL_FIREWATER,
        BLESSED_SUNFRUIT,
        DIRGES_KICKIN_CHIMAEROK_CHOPS,
        GRILLED_SQUID,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        SMOKED_DESERT_DUMPLINGS,
        TENDER_WOLF_STEAK,
    },
    ["HUNTER"] = {
        ELIXIR_OF_GREATER_AGILITY,
        ELIXIR_OF_THE_MONGOOSE,
        GROUND_SCORPOK_ASSAY,
        GRILLED_SQUID,
        TENDER_WOLF_STEAK,
    },
    ["MAGE"] = {
        ARCANE_ELIXIR,
        ELIXIR_OF_FROST_POWER,
        ELIXIR_OF_GREATER_FIREPOWER,
        FLASK_OF_SUPREME_POWER,
        GREATER_ARCANE_ELIXIR,
        CEREBRAL_CORTEX_COMPOUND,
        WINTERFALL_FIREWATER,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        TENDER_WOLF_STEAK,
    },
    ["PALADIN"] = {
        ELIXIR_OF_GIANTS,
        ELIXIR_OF_GREATER_AGILITY,
        ELIXIR_OF_THE_MONGOOSE,
        ELIXIR_OF_SUPERIOR_DEFENSE,
        FLASK_OF_DISTILLED_WISDOM,
        FLASK_OF_SUPREME_POWER,
        FLASK_OF_THE_TITANS,
        GIFT_OF_ARTHAS,
        GREATER_ARCANE_ELIXIR,
        MAGEBLOOD_POTION,
        LUNG_JUICE_COCKTAIL,
        GROUND_SCORPOK_ASSAY,
        CEREBRAL_CORTEX_COMPOUND,
        GIZZARD_GUM,
        ROIDS,
        JUJU_POWER,
        JUJU_MIGHT,
        WINTERFALL_FIREWATER,
        BLESSED_SUNFRUIT,
        DIRGES_KICKIN_CHIMAEROK_CHOPS,
        GRILLED_SQUID,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        SMOKED_DESERT_DUMPLINGS,
        TENDER_WOLF_STEAK,
    },
    ["PRIEST"] = {
        ARCANE_ELIXIR,
        FLASK_OF_DISTILLED_WISDOM,
        FLASK_OF_SUPREME_POWER,
        GREATER_ARCANE_ELIXIR,
        MAGEBLOOD_POTION,
        ELIXIR_OF_SHADOW_POWER,
        CEREBRAL_CORTEX_COMPOUND,
        GIZZARD_GUM,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        TENDER_WOLF_STEAK,
    },
    ["ROGUE"] = {
        ELIXIR_OF_GIANTS,
        ELIXIR_OF_GREATER_AGILITY,
        ELIXIR_OF_THE_MONGOOSE,
        FLASK_OF_THE_TITANS,
        GROUND_SCORPOK_ASSAY,
        ROIDS,
        JUJU_POWER,
        JUJU_MIGHT,
        WINTERFALL_FIREWATER,
        BLESSED_SUNFRUIT,
        GRILLED_SQUID,
        SMOKED_DESERT_DUMPLINGS,
        TENDER_WOLF_STEAK,
    },
    ["SHAMAN"] = {
        ARCANE_ELIXIR,
        ELIXIR_OF_GIANTS,
        ELIXIR_OF_THE_MONGOOSE,
        FLASK_OF_DISTILLED_WISDOM,
        FLASK_OF_SUPREME_POWER,
        FLASK_OF_THE_TITANS,
        GREATER_ARCANE_ELIXIR,
        MAGEBLOOD_POTION,
        LUNG_JUICE_COCKTAIL,
        GROUND_SCORPOK_ASSAY,
        CEREBRAL_CORTEX_COMPOUND,
        ROIDS,
        JUJU_POWER,
        JUJU_MIGHT,
        WINTERFALL_FIREWATER,
        BLESSED_SUNFRUIT,
        GRILLED_SQUID,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        SMOKED_DESERT_DUMPLINGS,
        TENDER_WOLF_STEAK,
    },
    ["WARLOCK"] = {
        ARCANE_ELIXIR,
        ELIXIR_OF_GREATER_FIREPOWER,
        ELIXIR_OF_SHADOW_POWER,
        FLASK_OF_SUPREME_POWER,
        GREATER_ARCANE_ELIXIR,
        CEREBRAL_CORTEX_COMPOUND,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        TENDER_WOLF_STEAK,
    },
    ["WARRIOR"] = {
        ELIXIR_OF_GIANTS,
        ELIXIR_OF_GREATER_AGILITY,
        ELIXIR_OF_THE_MONGOOSE,
        ELIXIR_OF_SUPERIOR_DEFENSE,
        FLASK_OF_THE_TITANS,
        GIFT_OF_ARTHAS,
        LUNG_JUICE_COCKTAIL,
        GROUND_SCORPOK_ASSAY,
        ROIDS,
        JUJU_POWER,
        JUJU_MIGHT,
        WINTERFALL_FIREWATER,
        BLESSED_SUNFRUIT,
        DIRGES_KICKIN_CHIMAEROK_CHOPS,
        GRILLED_SQUID,
        SMOKED_DESERT_DUMPLINGS,
        TENDER_WOLF_STEAK,
    },
}
