-- Flasks
FLASK_OF_THE_TITANS = 17626
FLASK_OF_SUPREME_POWER = 17628
FLASK_OF_DISTILLED_WISDOM = 17627
FLASK_OF_CHROMATIC_RESISTANCE = 17629

-- Blasted Lands Consumables
LUNG_JUICE_COCKTAIL = 10668
GROUND_SCORPOK_ASSAY = 10669
CEREBRAL_CORTEX_COMPOUND = 10692
GIZZARD_GUM = 10693

-- Elixirs
ARCANE_ELIXIR = 11390
ELIXIR_OF_GIANTS = 11405
ELIXIR_OF_THE_MONGOOSE = 17538
ELIXIR_OF_SUPERIOR_DEFENSE = 11348
GIFT_OF_ARTHAS = 11371
GREATER_ARCANE_ELIXIR = 17539
ELIXIR_OF_GREATER_FIREPOWER = 26276
ELIXIR_OF_SHADOW_POWER = 11474
ELIXIR_OF_FROST_POWER = 21920
MAGEBLOOD_POTION = 24363

-- Well Fed Buffs
-- Unique Buffs
BLESSED_SUNFRUIT = 18125
GRILLED_SQUID = 18192
NIGHTFIN_SOUP = 18194
RUNN_TUM_TUBER_SURPRISE = 22730

-- 12 sta/spi (all foods share the same buff)
TENDER_WOLF_STEAK = 19710

CONSUMABLES_BY_CLASSES = {
    ["DRUID"] = {
        ELIXIR_OF_GIANTS,
        ELIXIR_OF_THE_MONGOOSE,
        ELIXIR_OF_SUPERIOR_DEFENSE,
        GIFT_OF_ARTHAS,
        GREATER_ARCANE_ELIXIR,
        MAGEBLOOD_POTION,
        LUNG_JUICE_COCKTAIL,
        GROUND_SCORPOK_ASSAY,
        CEREBRAL_CORTEX_COMPOUND,
        GIZZARD_GUM,
        BLESSED_SUNFRUIT,
        GRILLED_SQUID,
        RUNN_TUM_TUBER_SURPRISE,
        TENDER_WOLF_STEAK,
    },
    ["HUNTER"] = {
        ELIXIR_OF_THE_MONGOOSE,
        GROUND_SCORPOK_ASSAY,
        GRILLED_SQUID,
        TENDER_WOLF_STEAK,
    },
    ["MAGE"] = {
        ARCANE_ELIXIR,
        ELIXIR_OF_FROST_POWER,
        GREATER_ARCANE_ELIXIR,
        CEREBRAL_CORTEX_COMPOUND,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        TENDER_WOLF_STEAK,
    },
    ["PALADIN"] = {
        ELIXIR_OF_GIANTS,
        ELIXIR_OF_THE_MONGOOSE,
        ELIXIR_OF_SUPERIOR_DEFENSE,
        GIFT_OF_ARTHAS,
        GREATER_ARCANE_ELIXIR,
        MAGEBLOOD_POTION,
        LUNG_JUICE_COCKTAIL,
        GROUND_SCORPOK_ASSAY,
        CEREBRAL_CORTEX_COMPOUND,
        GIZZARD_GUM,
        BLESSED_SUNFRUIT,
        GRILLED_SQUID,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        TENDER_WOLF_STEAK,
    },
    ["PRIEST"] = {
        ARCANE_ELIXIR,
        GREATER_ARCANE_ELIXIR,
        MAGEBLOOD_POTION,
        ELIXIR_OF_SHADOW_POWER,
        CEREBRAL_CORTEX_COMPOUND,
        GIZZARD_GUM,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        TENDER_WOLF_STEAK,
    },
    ["ROGUE"] = {
        ELIXIR_OF_GIANTS,
        ELIXIR_OF_THE_MONGOOSE,
        GROUND_SCORPOK_ASSAY,
        BLESSED_SUNFRUIT,
        GRILLED_SQUID,
        TENDER_WOLF_STEAK,
    },
    ["SHAMAN"] = {
        ARCANE_ELIXIR,
        ELIXIR_OF_GIANTS,
        ELIXIR_OF_THE_MONGOOSE,
        GREATER_ARCANE_ELIXIR,
        MAGEBLOOD_POTION,
        LUNG_JUICE_COCKTAIL,
        GROUND_SCORPOK_ASSAY,
        CEREBRAL_CORTEX_COMPOUND,
        BLESSED_SUNFRUIT,
        GRILLED_SQUID,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        TENDER_WOLF_STEAK,
    },
    ["WARLOCK"] = {
        ARCANE_ELIXIR,
        ELIXIR_OF_SHADOW_POWER,
        GREATER_ARCANE_ELIXIR,
        CEREBRAL_CORTEX_COMPOUND,
        NIGHTFIN_SOUP,
        RUNN_TUM_TUBER_SURPRISE,
        TENDER_WOLF_STEAK,
    },
    ["WARRIOR"] = {
        ELIXIR_OF_GIANTS,
        ELIXIR_OF_THE_MONGOOSE,
        ELIXIR_OF_SUPERIOR_DEFENSE,
        GIFT_OF_ARTHAS,
        LUNG_JUICE_COCKTAIL,
        GROUND_SCORPOK_ASSAY,
        BLESSED_SUNFRUIT,
        GRILLED_SQUID,
        TENDER_WOLF_STEAK,
    },
}